<?php
define('SYSTEM_EMAIL','HEROKU_EMAIL');
define('SYSTEM_EMAIL_PASSWORD','HEROKU_EMAIL_PASSWORD');

define('MYSQL_HOST','HEROKU_MYSQL_HOST');
define('MYSQL_USER','HEROKU_MYSQL_USER');
define('MYSQL_PASSWORD','HEROKU_MYSQL_PASSWORD');
define('MYSQL_DB','HEROKU_MYSQL_DB');

?>
